package pojos;
// Generated Jul 23, 2020 10:20:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Diadiem generated by hbm2java
 */
public class Diadiem  implements java.io.Serializable {


     private Integer ma;
     private String ten;
     private String diachi;
     private Integer succhua;
     private Set hoinghis = new HashSet(0);

    public Diadiem() {
    }

    public Diadiem(String ten, String diachi, Integer succhua, Set hoinghis) {
       this.ten = ten;
       this.diachi = diachi;
       this.succhua = succhua;
       this.hoinghis = hoinghis;
    }
   
    public Integer getMa() {
        return this.ma;
    }
    
    public void setMa(Integer ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public Integer getSucchua() {
        return this.succhua;
    }
    
    public void setSucchua(Integer succhua) {
        this.succhua = succhua;
    }
    public Set getHoinghis() {
        return this.hoinghis;
    }
    
    public void setHoinghis(Set hoinghis) {
        this.hoinghis = hoinghis;
    }




}


