package pojos;
// Generated Jul 23, 2020 10:20:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private Integer ma;
     private String ten;
     private String username;
     private String password;
     private String email;
     private String gioitinh;
     private String cmnd;
     private String sdt;
     private String loai;
     private String captruycap;
     private String thamgiahoinghi;
     private Set hoinghis = new HashSet(0);
     private Set thamgiahoinghis = new HashSet(0);

    public Taikhoan() {
    }

	
    public Taikhoan(String username) {
        this.username = username;
    }
    public Taikhoan(String ten, String username, String password, String email, String gioitinh, String cmnd, String sdt, String loai, String captruycap, String thamgiahoinghi, Set hoinghis, Set thamgiahoinghis) {
       this.ten = ten;
       this.username = username;
       this.password = password;
       this.email = email;
       this.gioitinh = gioitinh;
       this.cmnd = cmnd;
       this.sdt = sdt;
       this.loai = loai;
       this.captruycap = captruycap;
       this.thamgiahoinghi = thamgiahoinghi;
       this.hoinghis = hoinghis;
       this.thamgiahoinghis = thamgiahoinghis;
    }
   
    public Integer getMa() {
        return this.ma;
    }
    
    public void setMa(Integer ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getLoai() {
        return this.loai;
    }
    
    public void setLoai(String loai) {
        this.loai = loai;
    }
    public String getCaptruycap() {
        return this.captruycap;
    }
    
    public void setCaptruycap(String captruycap) {
        this.captruycap = captruycap;
    }
    public String getThamgiahoinghi() {
        return this.thamgiahoinghi;
    }
    
    public void setThamgiahoinghi(String thamgiahoinghi) {
        this.thamgiahoinghi = thamgiahoinghi;
    }
    public Set getHoinghis() {
        return this.hoinghis;
    }
    
    public void setHoinghis(Set hoinghis) {
        this.hoinghis = hoinghis;
    }
    public Set getThamgiahoinghis() {
        return this.thamgiahoinghis;
    }
    
    public void setThamgiahoinghis(Set thamgiahoinghis) {
        this.thamgiahoinghis = thamgiahoinghis;
    }




}


